name: CI

on: [push, pull_request]

jobs:
  test:
    name: Run tests
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f # 2.3.4
      - uses: actions/setup-dotnet@53063334342b67eb3f5066a7ac9151683aa30b96 # 1.8.0
        with:
          dotnet-version: 5.0.202
      - run: dotnet test
