name: CI

on: [push, pull_request]

jobs:
  test:
    name: Run tests
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633 # 2.3.5
      - uses: actions/setup-dotnet@607fce577a46308457984d59e4954e075820f10a # 1.8.0
        with:
          dotnet-version: 5.0.202
      - run: dotnet test
