name: CI

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    name: Run tests
    strategy:
      matrix:
        os: [ubuntu-20.04, windows-2022, macos-13]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683

      - name: Setup .NET
        uses: actions/setup-dotnet@3951f0dfe7a07e2313ec93c75700083e2005cbab
        with:
          dotnet-version: "5.0.202"
          cache: true
          cache-dependency-path: "**/packages.lock.json"

      - name: Restore packages
        run: dotnet restore --locked-mode

      - name: Run tests
        run: dotnet test
