name: Publish

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  publish:
    name: Publish NuGet package
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8

      - name: Publish NuGet packagse
        run: |
          dotnet pack --configuration release --include-symbols --output build src/Exercism.Tests
          dotnet pack --configuration release --include-symbols --output build src/Exercism.Tests.xunit.v3 
          dotnet nuget push --skip-duplicate --api-key ${{ secrets.NUGET_API_KEY }} --source https://www.nuget.org "**/*.nupkg"
